#pragma once

#define VIAL_KEYBOARD_UID {0xE1, 0x76, 0xBE, 0x69, 0x2F, 0x2B, 0x5E, 0x8A}
#define VIAL_UNLOCK_COMBO_ROWS {0,0}
#define VIAL_UNLOCK_COMBO_COLS {1,2}
#define ENCODERS_PAD_B { GP4, GP6 }
#define ENCODERS_PAD_A { GP5, GP12 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define DYNAMIC_KEYMAP_MACRO_COUNT 100
#define ENCODER_DIRECTION_FLIP